- name: Launch Master Node
  hosts:  all 
  become: true
  vars:
    non_root_user: ubuntu  # Replace with your non-root username
    master_ip_public: "{{ lookup('file', 'control_plane_ip') | trim }}"
  tasks:
    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Start k3s master node
      shell: |
          curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --disable servicelb --tls-san {{ master_ip_public }}" sh -s - --token u2Qw5PbXC887MMv85LeGSergeiChes
      args: 
        chdir: /tmp
        creates: /etc/systemd/system/k3s.service

    - name: Show kubeconfig in the terminal
      become: true
      shell: cat /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_content

    - name: Save kubeconfig content to file
      become: true
      delegate_to: localhost
      run_once: true
      copy:
        content: "{{ kubeconfig_content.stdout }}"
        dest: "{{ playbook_dir }}/kubeconfig"

    - name: Ensure the script is executable
      become: true
      delegate_to: localhost
      run_once: true
      file:
        path: "{{ playbook_dir }}/create_kubeconfig.sh"
        mode: '0755'

    - name: Execute the script to update the kubeconfig file
      become: true
      delegate_to: localhost
      run_once: true
      command: "{{ playbook_dir }}/create_kubeconfig.sh {{ playbook_dir }}/control_plane_ip {{ playbook_dir }}/kubeconfig"
      register: script_output

    - name: retreive the updated kubeconfig file
      become: true
      delegate_to: localhost
      shell: cat "{{ playbook_dir }}/kubeconfig"
      register: kubeconfig_proper_output

    - name: Print kubeconfig content
      debug:
        msg: "{{ kubeconfig_proper_output.stdout }}"

    - name: Ensure the /var/lib/jenkins/.kube/ directory exists
      become: true
      delegate_to: localhost
      file:
        path: "/var/lib/jenkins/.kube/"
        state: directory
        owner: 'jenkins'
        mode: '0755'
      
    - name: Copy k3s configuration file to jenkins workdir directory
      become: true
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ kubeconfig_proper_output.stdout }}"
        dest: "/var/lib/jenkins/.kube/config"
        owner: 'jenkins'
        mode: '0755'

    - name: Print script output
      become: true
      delegate_to: localhost
      run_once: true
      debug:
        msg: "{{ script_output.stdout }}"